carnet_auto/urls.py
from django.conf.urls import url

from carnet_auto import views

urlpatterns = [
    url(r'^$', views.Home.as_view(), name='home'),
    url(r'^ajout_voiture/$', views.AjoutVoiture.as_view(), name='ajout_voiture'),
    url(r'^edite_voiture/(?P<pk>[0-9]+)/$', views.EditeVoiture.as_view(), name='edite_voiture'),
    url(r'^supprime_voiture/(?P<pk>[0-9]+)/$', views.SupprimeVoiture.as_view(), name='supprime_voiture'),
    url(r'^voiture/(?P<pk>[0-9]+)/$', views.ManageVoiture.as_view(), name='voiture'),
    url(r'^voiture/(?P<pk>[0-9]+)/programme/$', views.ManageProgrammeMaintenance.as_view(), name='programme'),
    url(r'^voiture/(?P<pk>[0-9]+)/ajout_programme/$', views.AjoutProgrammeMaintenance.as_view(),
        name='ajout_programme'),
    url(r'^voiture/(?P<pk>[0-9]+)/edite_programme/(?P<pk_programme>[0-9]+)$', views.EditeProgrammeMaintenance.as_view(),
        name='edite_programme'),
    url(r'^voiture/(?P<pk>[0-9]+)/supprime_programme/(?P<pk_programme>[0-9]+)$',
        views.SupprimeProgrammeMaintenance.as_view(), name='supprime_programme'),
    url(r'^voiture/(?P<pk>[0-9]+)/ajout_revision/$', views.AjoutRevision.as_view(),
        name='ajout_revision'),
    url(r'^voiture/(?P<pk>[0-9]+)/edite_revision/(?P<pk_revision>[0-9]+)$', views.EditeRevision.as_view(),
        name='edite_revision'),
    url(r'^voiture/(?P<pk>[0-9]+)/supprime_revision/(?P<pk_revision>[0-9]+)$',
        views.SupprimeRevision.as_view(), name='supprime_revision'),
    url(r'^voiture/(?P<pk>[0-9]+)/supprime_operation/(?P<pk_operation>[0-9]+)$',
        views.SupprimeOperation.as_view(), name='supprime_operation'),
]

compta/urls.py
from django.conf.urls import url, include
from rest_framework import routers

from compta import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    # url(r'^', include(router.urls)),
    url(r'^$', views.Home.as_view(), name='home'),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^edit-categorie$', views.edit_categorie, name='edit-categorie'),
    url(r'^ajout-budget/$', views.AjoutBudget.as_view(), name='ajout-budget'),
    url(r'^edite-budget/(?P<pk>[0-9]+)/$', views.EditeBudget.as_view(), name='edite-budget'),
    url(r'^supprime-budget/(?P<pk>[0-9]+)/$', views.SupprimeBudget.as_view(), name='supprime-budget'),
    url(r'^apply-budget/$', views.apply_budget, name='apply-budget'),
    url(r'^compte/(?P<pk>[0-9]+)/details-calcule-a-verser$', views.details_calcule_a_verser, name='details-calcule-a-verser'),
    url(r'^set-revenus$', views.set_revenus, name='set-revenus'),
    url(r'^compte/(?P<pk>[0-9]+)/operations$', views.Operations.as_view(), name='operations'),
    url(r'^epargnes/(?P<categorie_id>[0-9]+)', views.OperationsEpargne.as_view(), name='voir-operations-epargnes'),
    url(r'^refresh$', views.refresh_comptes, name='refresh')
]

homelab/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth
from portail import views as portail

from portail.forms import BootstrapAuthenticationForm

urlpatterns = [
    url(r'^carnet-auto/', include('carnet_auto.urls', namespace='carnet_auto', app_name='carnet_auto')),
    url(r'^compta/', include('compta.urls', namespace='compta', app_name='compta')),
    url(r'^login/$', auth.login, {'authentication_form': BootstrapAuthenticationForm}, name='login'),
    url(r'^logout/$', auth.logout, {'next_page': 'login'}, name='logout'),
    url(r'^password_change/$', auth.password_change, name='password_change'),
    url(r'^password_change/done/$', auth.password_change_done, name='password_change_done'),
    url(r'^password_reset/$', auth.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth.password_reset_complete, name='password_reset_complete'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', portail.index, name='index'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carnet_auto/forms.py
from django import forms
from django.forms import ModelForm, ValidationError, CheckboxSelectMultiple
from django.utils.translation import ugettext_lazy as _
from extra_views import InlineFormSet

from carnet_auto.models import Voiture, ProgrammeMaintenance, Revision, Operation


class VoitureForm(ModelForm):
    class Meta:
        model = Voiture
        fields = ['nom', 'modele', 'immatriculation', 'kilometrage', 'date_mise_circulation', 'moyenne_km_annuel',
                  'prix_achat', 'date_achat', 'kilometrage_achat', 'photo']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['nom'].widget.attrs['autofocus'] = True
        self.fields['date_mise_circulation'].widget.attrs['class'] = 'datepicker'
        self.fields['date_achat'].widget.attrs['class'] = 'datepicker'

    def clean(self):
        cleaned_data = super().clean()

        # La date d'achat doit être inférieure à la date de mise en circulation
        if cleaned_data['date_achat'] is not None and cleaned_data['date_achat'] < cleaned_data[
            'date_mise_circulation']:
            raise ValidationError(_("La date d'achat ne peut pas précéder la date de mise en circulation"))

        return cleaned_data


class ProgrammeMaintenanceForm(ModelForm):
    class Meta:
        model = ProgrammeMaintenance
        fields = ['periodicite_kilometres', 'periodicite_annees', 'delai_alerte', 'delai_rappel', 'types_operations']
        widgets = {
            'types_operations': CheckboxSelectMultiple()
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['periodicite_kilometres'].widget.attrs['autofocus'] = True


class RevisionForm(ModelForm):
    class Meta:
        model = Revision
        fields = ['date', 'kilometrage']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['date'].widget.attrs['class'] = 'datepicker'


class OperationForm(ModelForm):
    id_operation_prevue = forms.IntegerField(required=False, min_value=0)

    class Meta:
        model = Operation
        fields = '__all__'


class AjoutOperationFormSet(InlineFormSet):
    form_class = OperationForm
    model = Operation
    extra = 1


class EditeOperationFormSet(AjoutOperationFormSet):
    extra = 0

carnet_auto/views.py
# Create your views here.
from datetime import date

from dateutil.relativedelta import relativedelta
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, TemplateView
from extra_views import CreateWithInlinesView, UpdateWithInlinesView

from carnet_auto.forms import VoitureForm, ProgrammeMaintenanceForm, RevisionForm, AjoutOperationFormSet, \
    EditeOperationFormSet
from carnet_auto.models import Voiture, Operation, ProgrammeMaintenance, Revision


class Home(ListView):
    model = Voiture
    template_name = 'carnet_auto/home.html'
    paginate_by = 10
    context_object_name = 'dernieres_operations'

    def get_queryset(self):
        return Operation.objects.get_all_dernieres_operations(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['voitures'] = Voiture.objects.get_voitures_for_user(self.request.user)
        return context

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class AjoutVoiture(CreateView):
    model = Voiture
    form_class = VoitureForm
    template_name = 'carnet_auto/voiture.html'
    success_url = reverse_lazy('carnet_auto:home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['creation'] = True
        return context

    def form_valid(self, form):
        form.instance.proprietaire = self.request.user
        form.instance.date_derniere_maj_km = date.today()
        return super().form_valid(form)

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class EditeVoiture(UpdateView):
    model = Voiture
    form_class = VoitureForm
    template_name = 'carnet_auto/voiture.html'
    success_url = reverse_lazy('carnet_auto:home')

    def get_queryset(self):
        # On vérifie que la voiture correspond bien à une voiture de l'utilisateur
        return super().get_queryset().filter(proprietaire=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['edition'] = True
        return context

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class SupprimeVoiture(DeleteView):
    model = Voiture
    success_url = reverse_lazy('carnet_auto:home')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class IndicateurEntretien():
    """Une énumération des différents indicateurs d'entretien pour un véhicule"""
    OK = 1
    WARN = 2
    NOK = 3


class ManageVoiture(TemplateView):
    template_name = 'carnet_auto/manage_voiture.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # On charge la voiture en prenant soin de regarder si elle appartient à l'utilisateur
        voiture = get_object_or_404(Voiture, pk=kwargs['pk'], proprietaire=self.request.user)

        # Récupération des opérations à prévoir
        context['operations_a_prevoir'] = Operation.objects.get_operations_a_prevoir(voiture)

        # Récupération des dernières opérations
        context['dernieres_operations'] = Operation.objects.get_dernieres_operations(voiture)

        context['voiture'] = voiture

        context['date_prochain_entretien'] = None
        context['indicateur_entretien'] = self.calculer_indicateur_entretien(context)

        if context['date_prochain_entretien'] is None:
            context['date_prochain_entretien'] = self.calculer_date_prochain_entretien_estime(context)

        context['IndicateurEntretien'] = IndicateurEntretien

        return context

    def calculer_indicateur_entretien(self, context):
        """Calcule l'indicateur d'entretien pour le véhicule en cours"""
        if context['operations_a_prevoir'].count() == 0:
            return IndicateurEntretien.OK

        closest_date = None
        for op in context['operations_a_prevoir']:
            if closest_date is None or closest_date > op.revision.date:
                closest_date = op.revision.date

        context['date_prochain_entretien'] = closest_date
        if closest_date >= date.today():
            return IndicateurEntretien.WARN
        return IndicateurEntretien.NOK

    def calculer_date_prochain_entretien_estime(self, context):
        """Calcule la date de prochain entretien estimée à partir du programme de maintenance et du nombre de km annuels
        renseigné"""
        progs = ProgrammeMaintenance.objects.get_programmes_for_voiture(voiture=context['voiture'])
        if progs.count() == 0:
            return None

        closest_date = None
        closest_km = None

        for prog in progs:
            for type_op in prog.types_operations.all():

                # On commence par calculer les dates et kilométrages à partir des valeurs actuelles au cas où il n'y a
                # pas d'opérations
                if prog.periodicite_annees is not None:
                    # FIXME Prendre quelle date en référence ? La date d'achat de la voiture si renseignée ?
                    date_calculee = date.today() + relativedelta(years=prog.periodicite_annees)
                    if closest_date is None or closest_date > date_calculee:
                        closest_date = date_calculee
                if prog.periodicite_kilometres is not None:
                    km = context['voiture'].get_estimation_kilometrage() + prog.periodicite_kilometres
                    if closest_km is None or closest_km > km:
                        closest_km = km

                # Les opérations étant classées par date décroissante, quand on trouve la première occurrence c'est qu'on
                # a la plus récente
                for op in context['dernieres_operations']:
                    if op.type.pk == type_op.pk:
                        if prog.periodicite_annees is not None:
                            date_calculee = op.revision.date + relativedelta(years=prog.periodicite_annees)
                            if closest_date is None or closest_date > date_calculee:
                                closest_date = date_calculee
                        if prog.periodicite_kilometres is not None:
                            km = op.revision.kilometrage + prog.periodicite_kilometres
                            if closest_km is None or closest_km > km:
                                closest_km = km
                        break

        # Calcul de la date théorique à partir du kilométrage pour voir si elle est supérieure à celle calculée à partir
        # des périodicités à l'années
        if closest_km is not None:
            diff = closest_km - context['voiture'].get_estimation_kilometrage()
            nb_jours = diff / (context['voiture'].moyenne_km_annuel / 365)
            date_calculee = date.today() + relativedelta(days=nb_jours)
            if closest_date is None or closest_date > date_calculee:
                closest_date = date_calculee

        return closest_date

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class ManageProgrammeMaintenance(ListView):
    model = ProgrammeMaintenance
    paginate_by = 20
    context_object_name = 'programmes'
    template_name = 'carnet_auto/manage_programme.html'

    def get_queryset(self):
        return ProgrammeMaintenance.objects.get_programmes_for_voiture(voiture_pk=self.kwargs['pk'],
                                                                       user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        voiture = get_object_or_404(Voiture, pk=self.kwargs['pk'], proprietaire=self.request.user)
        context['voiture'] = voiture
        return context

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class AjoutProgrammeMaintenance(CreateView):
    model = ProgrammeMaintenance
    form_class = ProgrammeMaintenanceForm
    template_name = 'carnet_auto/programme.html'
    context_object_name = 'programme'

    def get_success_url(self):
        return reverse_lazy('carnet_auto:programme', kwargs={'pk': self.kwargs['pk']})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['creation'] = True
        context['pk_voiture'] = self.kwargs['pk']
        return context

    def form_valid(self, form):
        form.instance.voiture = Voiture.objects.get(pk=self.kwargs['pk'], proprietaire=self.request.user)
        return super().form_valid(form)

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class EditeProgrammeMaintenance(UpdateView):
    model = ProgrammeMaintenance
    form_class = ProgrammeMaintenanceForm
    template_name = 'carnet_auto/programme.html'
    pk_url_kwarg = 'pk_programme'
    context_object_name = 'programme'

    def get_success_url(self):
        return reverse_lazy('carnet_auto:programme', kwargs={'pk': self.kwargs['pk']})

    def get_queryset(self):
        # On vérifie que la voiture correspond bien à une voiture de l'utilisateur
        return super().get_queryset().filter(voiture__proprietaire=self.request.user)

    def get_context_data(self, **kwargs):

carnet_auto/templates/carnet_auto/manage_voiture.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load bootstrap3 %}
{% load utils %}

{% block navbar-content %}
    <div class="navbar-left">
        <a class="btn btn-default navbar-btn" href="{% url 'carnet_auto:home' %}">{% trans "Retour" %}</a>
        <a href="{% url 'carnet_auto:ajout_revision' pk=voiture.pk %}"
           class="btn btn-primary navbar-btn">{% trans "Enregistrer une révision" %}</a>
    </div>
{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title text-center">{{ voiture.nom }}</h3>
                    </div>

                    <div class="panel-body">
                        <img src="{% if voiture.photo %}{% get_media_prefix %}{{ voiture.photo }}{% else %}{% static "img/megane.jpg" %}{% endif %}"
                             class="img-thumbnail"/>
                    </div>

                    <div class="panel-footer">
                        <div class="text-center">
                            <a href="{% url 'carnet_auto:edite_voiture' pk=voiture.pk %}"
                               class="btn btn-primary btn-sm">{% trans "Editer la voiture" %}</a>
                            <button type="button" data-toggle="modal" data-target="#confirmeSuppression"
                                    class="btn btn-danger btn-sm">{% trans "Supprimer la voiture" %}</button>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-8">
                <div class="row">
                    <h4>{% trans "Entretien" %} :
                        {% if indicateur_entretien == IndicateurEntretien.OK %}
                            {% if date_prochain_entretien == None %}
                                <span class="text-warning">{% bootstrap_icon "warning-sign" %} {% trans "Aucun programme enregistré" %} <a
                                    class="button badge" data-toggle="tooltip" data-placement="right"
                                    title="{% trans "Aucun programme de maintenance n'a été enregistré pour ce véhicule" %}">?</a></span>
                            {% else %}
                                <span class="text-success">{% bootstrap_icon "ok" %} {% trans "OK !" %} <a
                                    class="button badge" data-toggle="tooltip" data-placement="right"
                                    title="{% trans "Aucun entretien n'est prévu à ce jour" %}">?</a></span>
                            {% endif %}
                        {% elif indicateur_entretien == IndicateurEntretien.WARN %}
                            <span class="text-warning">{% bootstrap_icon "warning-sign" %} {% trans "Entretien(s) à prévoir" %} <a
                                class="button badge" data-toggle="tooltip" data-placement="right"
                                title="{% trans "Un ou plusieurs entretien(s) sont dores et déjà prévue pour une date ultérieure à celle du jour" %}">?</a></span>
                        {% else %}
                            <span class="text-danger">{% bootstrap_icon "remove" %} {% trans "Entretien(s) retardé(s)" %} <a
                                class="button badge" data-toggle="tooltip" data-placement="right"
                                title="{% trans "Un ou plusieurs entretien(s) sont à effectuer le plus rapidement possible" %}">?</a></span>
                        {% endif %}

                    </h4>
                </div>

                <div class="row">
                    {% if indicateur_entretien == IndicateurEntretien.OK %}
                        <h4>{% trans "Prochain entretien estimé" %} :
                            {% if date_prochain_entretien == None %}
                                <span class="text-warning">{% bootstrap_icon "warning-sign" %} {% trans "Aucun programme enregistré" %} <a
                                    class="button badge" data-toggle="tooltip" data-placement="right"
                                    title="{% trans "Aucun programme de maintenance n'a été enregistré pour ce véhicule" %}">?</a></span>
                            {% else %}
                                <span class="text-success">{{ date_prochain_entretien }} <a
                                    class="button badge" data-toggle="tooltip" data-placement="right"
                                    title="{% trans "La date de prochain entretien estimé est calculée sur la base du nombre de kilomètres annuels que vous avez renseigné" %}">?</a></span>
                            {% endif %}
                        </h4>
                    {% else %}
                        <h4>{% trans "Prochain entretien" %} :
                            {% if indicateur_entretien == IndicateurEntretien.WARN %}
                                <span class="text-warning">{{ date_prochain_entretien }} <a
                                    class="button badge" data-toggle="tooltip" data-placement="right"
                                    title="{% trans "La date de prochain entretien est la date de la révision à effectuer la plus ancienne" %}">?</a></span>
                            {% else %}
                                <span class="text-danger">{{ date_prochain_entretien }} <a
                                    class="button badge" data-toggle="tooltip" data-placement="right"
                                    title="{% trans "La date de prochain entretien est la date (déjà dépassée) à laquelle vous auriez dû effectuer des opérations" %}">?</a></span>
                            {% endif %}
                        </h4>
                    {% endif %}
                </div>

                <div class="row">
                    <a href="{% url 'carnet_auto:programme' pk=voiture.pk %}"
                        class="btn btn-primary navbar-btn">{% trans "Gérer le programme de maintenance" %}</a>
                </div>
            </div>
        </div>

        <p class="lead text-center">
            {% trans "Opérations à effectuer" %}
        </p>

         <div class="row">
            <div class="col-md-offset-1 col-md-10">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>{% trans "Opération" %}</th>
                        <th>{% trans "Date" %}</th>
                        <th>{% trans "Kilométrage" %}</th>
                        <th>{% trans "Etat" %}</th>
                        <th>{% trans "Actions" %}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for operation in operations_a_prevoir %}
                        <tr>
                            <td>{{ operation.type.nom }}</td>
                            <td>{{ operation.revision.date }}</td>
                            <td>{{ operation.revision.kilometrage }}</td>
                            {% if operation.effectue %}
                                <td><span class="label label-success">{% trans "Effectué" %}</span></td>
                            {% else %}
                                <td><span class="label label-warning">{% trans "A prévoir" %}</span></td>
                            {% endif %}
                            <td>
                                <a href="{% url 'carnet_auto:edite_revision' pk=voiture.pk pk_revision=operation.revision.id %}"
                                    class="btn btn-primary btn-xs">{% trans "Editer" %}</a>
                                <button type="button" data-toggle="modal" data-target="#confirmeSuppressionOperation"
                                        onclick="$('#confirmeSuppressionOperationForm').attr('action', '{% url 'carnet_auto:supprime_operation' pk=voiture.pk pk_operation=operation.pk %}');"
                                    class="btn btn-danger btn-xs">{% trans "Supprimer" %}</button>
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td class="text-center" colspan="5">{% trans "Aucune opération encore enregistrée !" %}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        <p class="lead text-center">
            {% trans "Dernières opérations" %}
        </p>

         <div class="row">
            <div class="col-md-offset-1 col-md-10">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>{% trans "Opération" %}</th>
                        <th>{% trans "Date" %}</th>
                        <th>{% trans "Kilométrage" %}</th>
                        <th>{% trans "Etat" %}</th>
                        <th>{% trans "Actions" %}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for operation in dernieres_operations %}
                        <tr>
                            <td>{{ operation.type.nom }}</td>
                            <td>{{ operation.revision.date }}</td>
                            <td>{{ operation.revision.kilometrage }}</td>
                            {% if operation.effectue %}
                                <td><span class="label label-success">{% trans "Effectué" %}</span></td>
                            {% else %}
                                <td><span class="label label-warning">{% trans "A prévoir" %}</span></td>
                            {% endif %}
                            <td>
                                <a href="{% url 'carnet_auto:edite_revision' pk=voiture.pk pk_revision=operation.revision.id %}"
                                    class="btn btn-primary btn-xs">{% trans "Editer" %}</a>
                                <button type="button" data-toggle="modal" data-target="#confirmeSuppressionOperation"
                                        onclick="$('#confirmeSuppressionOperationForm').attr('action', '{% url 'carnet_auto:supprime_operation' pk=voiture.pk pk_operation=operation.pk %}');"
                                    class="btn btn-danger btn-xs">{% trans "Supprimer" %}</button>
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td class="text-center" colspan="5">{% trans "Aucune opération encore enregistrée !" %}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>


    <div class="modal fade" role="dialog" id="confirmeSuppression">
        <div class="modal-dialog">
            <form class="modal-content" method="post" action="{% url 'carnet_auto:supprime_voiture' pk=voiture.pk %}">
                {% csrf_token %}
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">{% trans "Confirmation suppression" %}</h4>
                </div>
                <div class="modal-body">
                    <p>{% trans "Êtes-vous sûr de vouloir supprimer cette voiture ? Les données de celles-ci seront effacées définitivement !" %}</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Non" %}</button>
                    <button type="submit" class="btn btn-danger">{% trans "Oui" %}</button>
                </div>
            </form>
        </div>
    </div>

    <div class="modal fade" role="dialog" id="confirmeSuppressionOperation">
        <div class="modal-dialog">
            <form id="confirmeSuppressionOperationForm" class="modal-content" method="post">
                {% csrf_token %}
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">{% trans "Confirmation suppression" %}</h4>
                </div>
                <div class="modal-body">
                    <p>{% trans "Êtes-vous sûr de vouloir supprimer cette opération ?" %}</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Non" %}</button>
                    <button type="submit" class="btn btn-danger">{% trans "Oui" %}</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

carnet_auto/templates/carnet_auto/programme.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load bootstrap3 %}
{% load utils %}

{% block navbar-content %}
    <div class="navbar-left">
        <a class="btn btn-default navbar-btn" href="{% if creation %}{% url 'carnet_auto:programme' pk=pk_voiture %}{% else %}{% url 'carnet_auto:programme' pk=programme.voiture.pk %}{% endif %}">{% trans "Retour" %}</a>
    </div>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <form method="post" action="{% if creation %}{% url 'carnet_auto:ajout_programme' pk=pk_voiture %}{% else %}{% url 'carnet_auto:edite_programme' pk=programme.voiture.pk pk_programme=programme.pk %}{% endif %}">
                {% csrf_token %}
                <div class="col-md-12">
                    <p class="lead text-center">
                        {% if creation %}{% trans "Ajout d'un programme de maintenance" %}{% elif edition %}
                            {% trans "Edition d'un programme de maintenance" %}{% endif %}
                    </p>

                    <div class="form-horizontal">
                        {% bootstrap_form form layout='horizontal' %}
                    </div>

                    <div class="pull-right">
                        <button type="submit" class="btn btn-primary">{% trans "Valider la saisie" %}</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}