compta/urls.py
from django.conf.urls import url, include
from rest_framework import routers

from compta import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    # url(r'^', include(router.urls)),
    url(r'^$', views.Home.as_view(), name='home'),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^edit-categorie$', views.edit_categorie, name='edit-categorie'),
    url(r'^ajout-budget/$', views.AjoutBudget.as_view(), name='ajout-budget'),
    url(r'^edite-budget/(?P<pk>[0-9]+)/$', views.EditeBudget.as_view(), name='edite-budget'),
    url(r'^supprime-budget/(?P<pk>[0-9]+)/$', views.SupprimeBudget.as_view(), name='supprime-budget'),
    url(r'^apply-budget/$', views.apply_budget, name='apply-budget'),
    url(r'^compte/(?P<pk>[0-9]+)/details-calcule-a-verser$', views.details_calcule_a_verser, name='details-calcule-a-verser'),
    url(r'^set-revenus$', views.set_revenus, name='set-revenus'),
    url(r'^compte/(?P<pk>[0-9]+)/operations$', views.Operations.as_view(), name='operations'),
    url(r'^epargnes/(?P<categorie_id>[0-9]+)', views.OperationsEpargne.as_view(), name='voir-operations-epargnes'),
    url(r'^refresh$', views.refresh_comptes, name='refresh')
]

homelab/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth
from portail import views as portail

from portail.forms import BootstrapAuthenticationForm

urlpatterns = [
    url(r'^carnet-auto/', include('carnet_auto.urls', namespace='carnet_auto', app_name='carnet_auto')),
    url(r'^compta/', include('compta.urls', namespace='compta', app_name='compta')),
    url(r'^login/$', auth.login, {'authentication_form': BootstrapAuthenticationForm}, name='login'),
    url(r'^logout/$', auth.logout, {'next_page': 'login'}, name='logout'),
    url(r'^password_change/$', auth.password_change, name='password_change'),
    url(r'^password_change/done/$', auth.password_change_done, name='password_change_done'),
    url(r'^password_reset/$', auth.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth.password_reset_complete, name='password_reset_complete'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', portail.index, name='index'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portail/models.py
from django.db import models

# Create your models here.

portail/forms.py
from django.contrib.auth.forms import AuthenticationForm


class BootstrapAuthenticationForm(AuthenticationForm):
    def __init__(self, request=None, *args, **kwargs):
        super().__init__(request, *args, **kwargs)
        self.fields['username'].widget.attrs['autofocus'] = True

portail/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render


# Create your views here.
@login_required
def index(request):
    return render(request, 'index.html')

portail/templates/base.html
{% extends 'bootstrap3/bootstrap3.html' %}
{% load i18n %}
{% load static %}
{% load bootstrap3 %}
{% load utils %}
{% block bootstrap3_title %}{% trans "Homelab" %}{% endblock %}
{% block bootstrap3_extra_head %}
    <link href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker.min.css"
          rel="stylesheet">
    <link href="{% static 'css/homelab.css' %}" rel="stylesheet">
{% endblock %}

{% block bootstrap3_content %}

    {% if user.is_authenticated %}
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-toggle" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                    <a class="navbar-brand" href="{% url 'index' %}"><span class="navbar-title">{% trans "Homelab" %}<br><sup><small>v{{ APP_VERSION }}</small></sup></span></a>
                </div>
                <div class="collapse navbar-collapse" id="navbar-toggle">
                    {% block navbar-content %}{% endblock %}
                    <div class="navbar-right">
                    <span class="navbar-text">{% blocktrans with name=user.get_full_name %}Bonjour {{ name }}
                        !{% endblocktrans %}</span>
                        <a href="{% url 'logout' %}" class="btn btn-default navbar-btn">{% trans "Se déconnecter" %}</a>
                    </div>
                </div>
            </div>
        </nav>
    {% endif %}

    {% block content %}{% endblock %}

{% endblock %}

{% block bootstrap3_extra_script %}
    <script type="text/javascript"
            src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
    {% if request.LANGUAGE_CODE %}
        <script type="text/javascript"
                src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/locales/bootstrap-datepicker.{{ request.LANGUAGE_CODE }}.min.js"></script>
        <script type="text/javascript">
            $('.datepicker').datepicker({
                language: '{{ request.LANGUAGE_CODE }}'
            });
        </script>
    {% else %}
        <script type="text/javascript"
                src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/locales/bootstrap-datepicker.fr.min.js"></script>
        <script type="text/javascript">
            $('.datepicker').datepicker({
                language: 'fr'
            });
        </script>
    {% endif %}
    <script type="text/javascript" src="{% static 'js/homelab.js' %}"></script>
    {% block extra_script %}{% endblock %}
{% endblock %}

portail/templates/index.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load bootstrap3 %}
{% load utils %}

{% block content %}
    <div class="container">
        <div class="col-md-4">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title text-center">{% trans "Carnet d'entretien automobile" %}</h3>
                </div>

                <div class="panel-body">
                    <a href="{% url 'carnet_auto:home' %}" class="thumbnail">
                        <img src="{% static "img/megane.jpg" %}" style="height: 200px;"/>
                    </a>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title text-center">{% trans "Comptabilité" %}</h3>
                </div>

                <div class="panel-body">
                    <a href="{% url 'compta:home' %}" class="thumbnail">
                        <img src="{% static "img/compta.jpg" %}" style="height: 200px;"/>
                    </a>
                </div>
            </div>
        </div>
        {% if user.is_superuser %}
        <div class="col-md-4">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title text-center">{% trans "Administration" %}</h3>
                </div>

                <div class="panel-body">
                    <a href="{% url 'admin:index' %}" class="thumbnail">
                        <img src="{% static "img/admin.png" %}" style="height: 200px;"/>
                    </a>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
{% endblock %}