compta/urls.py
from django.conf.urls import url, include
from rest_framework import routers

from compta import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    # url(r'^', include(router.urls)),
    url(r'^$', views.Home.as_view(), name='home'),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^edit-categorie$', views.edit_categorie, name='edit-categorie'),
    url(r'^ajout-budget/$', views.AjoutBudget.as_view(), name='ajout-budget'),
    url(r'^edite-budget/(?P<pk>[0-9]+)/$', views.EditeBudget.as_view(), name='edite-budget'),
    url(r'^supprime-budget/(?P<pk>[0-9]+)/$', views.SupprimeBudget.as_view(), name='supprime-budget'),
    url(r'^apply-budget/$', views.apply_budget, name='apply-budget'),
    url(r'^compte/(?P<pk>[0-9]+)/details-calcule-a-verser$', views.details_calcule_a_verser, name='details-calcule-a-verser'),
    url(r'^set-revenus$', views.set_revenus, name='set-revenus'),
    url(r'^compte/(?P<pk>[0-9]+)/operations$', views.Operations.as_view(), name='operations'),
    url(r'^epargnes/(?P<categorie_id>[0-9]+)', views.OperationsEpargne.as_view(), name='voir-operations-epargnes'),
    url(r'^refresh$', views.refresh_comptes, name='refresh')
]

homelab/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth
from portail import views as portail

from portail.forms import BootstrapAuthenticationForm

urlpatterns = [
    url(r'^carnet-auto/', include('carnet_auto.urls', namespace='carnet_auto', app_name='carnet_auto')),
    url(r'^compta/', include('compta.urls', namespace='compta', app_name='compta')),
    url(r'^login/$', auth.login, {'authentication_form': BootstrapAuthenticationForm}, name='login'),
    url(r'^logout/$', auth.logout, {'next_page': 'login'}, name='logout'),
    url(r'^password_change/$', auth.password_change, name='password_change'),
    url(r'^password_change/done/$', auth.password_change_done, name='password_change_done'),
    url(r'^password_reset/$', auth.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth.password_reset_complete, name='password_reset_complete'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', portail.index, name='index'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

compta/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from compta.models import Budget, OperationEpargne, Operation, CategorieEpargne


class BudgetForm(forms.ModelForm):
    class Meta:
        model = Budget
        fields = ['categorie', 'compte_associe', 'budget', 'solde_en_une_fois']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['budget'].widget.attrs['autofocus'] = True


class OperationCategoriesForm(forms.Form):
    operation_id = forms.IntegerField(required=True, widget=forms.HiddenInput())
    categorie = forms.ChoiceField(required=False, choices=(("", ""),))
    redirect = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput())

    def __init__(self, post, render_initial=True):
        if render_initial:
            super().__init__()
        else:
            super().__init__(post)

        operation = post.get('operation')
        categories_epargne = post.get('categories_epargne')
        redirect = post.get('redirect')
        operation_id = post.get('operation_id')

        if redirect is not None:
            self.fields['redirect'].initial = redirect
            if redirect:
                self.fields['categorie'].widget = forms.HiddenInput()
                self.fields['categorie'].initial = ""

        if operation is None and operation_id is not None:
            if render_initial:
                self.fields['operation_id'].initial = post.get('operation_id')
            else:
                operation = Operation.objects.get(pk=int(operation_id))

        if operation is not None:
            operation.load_categorie()

            if operation.categorie_id is not None:
                self.fields['categorie'].initial = operation.categorie_id

            self.fields['operation_id'].initial = operation.pk
            if operation.compte.epargne:
                self.fields['categorie'].choices += (("-1", _("Partagé entre les différentes catégories")),)
                if categories_epargne is None:
                    categories_epargne = CategorieEpargne.objects.all().order_by('libelle')
                for categorie in categories_epargne:
                    self.fields['categorie'].choices += ((str(categorie.pk).replace(" ", ""), categorie.libelle),)
            else:
                self.fields['categorie'].choices += (("-1", _("Hors Budget")),)
                self.fields['categorie'].choices += (("-2", _("Revenue")),)
                self.fields['categorie'].choices += (("-3", _("Avance sur débit(s) futur(s)")),)
                if operation.compte.utilisateurs.count() > 1:
                    for utilisateur in operation.compte.utilisateurs.all():
                        self.fields['categorie'].choices += (("c" + str(-1000 - utilisateur.pk).replace(' ', ''),
                                                              _("Contribution") + " " + utilisateur.first_name),)
                    for utilisateur in operation.compte.utilisateurs.all():
                        self.fields['categorie'].choices += (("a" + str(-1000 - utilisateur.pk).replace(' ', ''), _(
                            "Contribution (avances)") + " " + utilisateur.first_name),)
                for budget in operation.compte.budget_set.all():
                    self.fields['categorie'].choices += ((budget.pk, budget.categorie.libelle),)
        else:
            self.fields['operation_id'].initial = post.get('operation_id')

        self.fields['categorie'].choices = sorted(self.fields['categorie'].choices, key=lambda x: x[1])

compta/views.py
import datetime

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, Group
from django.http import Http404
from django.http import HttpResponse
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView
from django.views.generic import DeleteView
from django.views.generic import ListView
from django.views.generic import TemplateView
from django.views.generic import UpdateView
from rest_framework import viewsets

from compta.forms import BudgetForm, OperationCategoriesForm
from compta.management.commands import check_operations
from compta.models import Operation, Categorie, Compte, Budget, CategorieEpargne, OperationEpargne, Epargne
from compta.serializers import UserSerializer, GroupSerializer


class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer


class GroupViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Group.objects.all()
    serializer_class = GroupSerializer


class Index(TemplateView):
    template_name = 'index.html'

    # @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


@login_required
def apply_budget(request):
    if request.method == 'POST':
        budget_id = request.POST['budget_id']
        budget_value = request.POST['budget_value'].replace(',', '.')

        try:
            if budget_value is not None:
                budget = Budget.objects.get(pk=budget_id)
                budget.budget = budget_value
                budget.save()
        except Budget.DoesNotExist:
            raise Http404()

        return redirect('compta:home')

    return HttpResponse("NOK", status=400)


@method_decorator(login_required, name='dispatch')
class AjoutBudget(CreateView):
    model = Budget
    form_class = BudgetForm
    template_name = 'compta/budget.html'
    success_url = reverse_lazy('compta:home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['creation'] = True
        return context


@method_decorator(login_required, name='dispatch')
class EditeBudget(UpdateView):
    model = Budget
    form_class = BudgetForm
    template_name = 'compta/budget.html'
    success_url = reverse_lazy('compta:home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['edition'] = True
        return context


@method_decorator(login_required, name='dispatch')
class SupprimeBudget(DeleteView):
    model = Budget
    success_url = reverse_lazy('compta:home')


@login_required
def details_calcule_a_verser(request, pk):
    compte = get_object_or_404(Compte, pk=pk, utilisateurs=request.user)
    compte.calculer_parts()
    return render(request, 'compta/details_calcule_a_verser.html', locals())


@login_required
def set_revenus(request):
    if request.method == 'POST':
        revenus = float(request.POST['revenus'])
        operation_id_saisie_manuelle = request.POST['operation_id_saisie_manuelle']

        operation = Operation() if operation_id_saisie_manuelle == '' else Operation.objects.get(
            pk=int(operation_id_saisie_manuelle))
        operation.raz_categorie()
        operation.libelle = 'Revenus ' + request.user.get_full_name()
        operation.date_operation = datetime.date.today()
        operation.date_valeur = operation.date_operation
        operation.montant = revenus
        operation.compte = Compte.objects.get(utilisateurs=request.user)
        operation.recette = request.user
        operation.saisie_manuelle = True
        operation.save()

        return redirect('compta:home')

    return HttpResponse("NOK", status=400)


@method_decorator(login_required, name='dispatch')
class Home(ListView):
    model = Operation
    template_name = 'compta/home.html'
    paginate_by = 10
    context_object_name = 'operations_a_categoriser'

    def get_queryset(self):
        return Operation.objects.filter(compte__utilisateurs=self.request.user, budget__isnull=True, hors_budget=False,
                                        recette_id__isnull=True, contributeur_id__isnull=True,
                                        avance_debit=False).order_by('date_operation')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['today'] = datetime.date.today()
        if self.request.GET and self.request.GET['mois'] and self.request.GET['annee']:
            context['today'] = context['today'].replace(day=1, month=int(self.request.GET['mois']),
                                                        year=int(self.request.GET['annee']))
        context['available_years'] = range(2017, 2025)
        context['categories'] = Categorie.objects.all().order_by('libelle')
        context['categories_epargne'] = CategorieEpargne.objects.all().order_by('libelle')
        context['comptes'] = Compte.objects.filter(utilisateurs=self.request.user).order_by('libelle')
        context['epargnes'] = Epargne.objects.filter(utilisateurs=self.request.user).order_by('categorie__libelle')

        self.request.user.revenus_personnels = self.request.user.get_revenus_personnels(context['today'])
        self.request.user.revenus_personnels_saisis_manuellement = self.request.user.get_revenus_personnels_saisis_manuellement(
            context['today'])

        context['total_epargnes'] = 0
        context['total_epargne_reel'] = 0
        context['total_pourcentage_epargne'] = 0

        for epargne in context['epargnes']:
            context['total_epargnes'] += epargne.solde
            context['total_pourcentage_epargne'] += epargne.pourcentage_alloue

        context['comptes_budget'] = list()

        for compte in context['comptes']:
            compte.calculer_parts(context['today'])

            for user in compte.utilisateurs_list:
                if user.pk == self.request.user.pk:
                    compte.utilisateur = user
                    break

            # Vérification que le total des comptes épargnes est égal au total_epargne
            if compte.epargne:
                context['total_epargne_reel'] += compte.solde

            for budget in compte.budgets:
                budget.hidden = budget.solde == 0 or budget.solde_en_une_fois and budget.depenses == 0
                budget.warning = budget.solde_en_une_fois and budget.depenses > 0 and budget.solde > 0
                budget.danger = budget.solde_en_une_fois and budget.depenses > 0 and budget.solde < 0

                for operation in budget.operations:
                    operation.create_hidden_empty_form(redirect=True)

            if compte.budgets:
                context['comptes_budget'].append(compte)

        for operation in context['operations_a_categoriser']:
            operation.create_form(categories_epargne=context['categories_epargne'])

        return context


@method_decorator(login_required, name='dispatch')
class OperationsEpargne(ListView):
    model = OperationEpargne
    template_name = 'compta/operations_epargne.html'
    paginate_by = 10
    context_object_name = 'operations'

    def get_queryset(self):
        return OperationEpargne.objects.filter(epargne__utilisateurs=self.request.user,
                                               epargne_id=self.kwargs['categorie_id']) \
            .order_by('-operation__date_operation')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['epargne'] = get_object_or_404(Epargne, pk=self.kwargs['categorie_id'], utilisateurs=self.request.user)
        for operation in context['operations']:
            operation.part = operation.montant / operation.operation.montant
        return context


@method_decorator(login_required, name='dispatch')
class Operations(ListView):
    model = Operation
    template_name = 'compta/operations.html'
    paginate_by = 10
    context_object_name = 'operations'

    def get_queryset(self):
        return Operation.objects.filter(compte__utilisateurs=self.request.user, compte=self.kwargs['pk']).order_by(
            '-date_operation')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['compte'] = get_object_or_404(Compte, pk=self.kwargs['pk'], utilisateurs=self.request.user)
        context['categories_epargne'] = CategorieEpargne.objects.all().order_by('libelle')

        for operation in context['operations']:
            operation.create_form(categories_epargne=context['categories_epargne'])
        return context


@login_required
def edit_categorie(request):
    if request.method == 'POST':
        form = OperationCategoriesForm(request.POST, render_initial=False)
        if form.is_valid():
            operation_id = form.cleaned_data['operation_id']
            categorie_id = form.cleaned_data['categorie']
            want_redirect = form.cleaned_data['redirect']

            try:
                operation = Operation.objects.get(pk=operation_id, compte__utilisateurs=request.user)
                operation.save_categorie(categorie_id, request.user)
            except Operation.DoesNotExist or OperationEpargne.DoesNotExist or Epargne.DoesNotExist:
                raise Http404()

            if want_redirect:
                return redirect('compta:home')
            return HttpResponse("OK")

    return HttpResponse("NOK", status=400)


@login_required
def refresh_comptes(request):
    check_operations.check_operations()
    return HttpResponse("OK")

compta/templates/compta/budget.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load bootstrap3 %}
{% load utils %}

{% block navbar-content %}
    <div class="navbar-left">
        <a class="btn btn-default navbar-btn" href="{% url 'compta:home' %}">{% trans "Retour" %}</a>
        {% if edition %}
            {# FIXME: La suppression supprime en cascade les opérations assignées au budget #}
{#            <button type="button" data-toggle="modal" data-target="#confirmeSuppression"#}
{#                                    class="btn btn-danger btn-sm">{% trans "Supprimer le budget" %}</button>#}
        {% endif %}
    </div>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <form enctype="multipart/form-data" method="post" action="{% if creation %}{% url 'compta:ajout-budget' %}{% elif edition %}{% url 'compta:edite-budget' pk=budget.pk %}{% endif %}">
                {% csrf_token %}
                <div class="col-md-12">
                    <p class="lead text-center">{% if creation %}{% trans "Ajout d'un budget" %}{% else %}
                        {% trans "Edition d'un budget" %}{% endif %}</p>

                    <div class="form-horizontal">
                        {% bootstrap_form_errors form %}
                        {% bootstrap_field form.categorie layout='horizontal' %}
                        {% bootstrap_field form.compte_associe layout='horizontal' %}
                        {% bootstrap_field form.budget layout='horizontal' %}
                        {% bootstrap_field form.solde_en_une_fois layout='horizontal' %}
                    </div>

                    <div class="pull-right">
                        <button type="submit" class="btn btn-primary">{% trans "Valider la saisie" %}</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    {% if edition %}
    <div class="modal fade" role="dialog" id="confirmeSuppression">
        <div class="modal-dialog">
            <form class="modal-content" method="post" action="{% url 'compta:supprime-budget' pk=budget.pk %}">
                {% csrf_token %}
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">{% trans "Confirmation suppression" %}</h4>
                </div>
                <div class="modal-body">
                    <p>{% trans "Êtes-vous sûr de vouloir supprimer ce budget ? Les données de celui-ci seront effacées définitivement !" %}</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Non" %}</button>
                    <button type="submit" class="btn btn-danger">{% trans "Oui" %}</button>
                </div>
            </form>
        </div>
    </div>
    {% endif %}
{% endblock %}

compta/templates/compta/details_calcule_a_verser.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load bootstrap3 %}
{% load utils %}

{% block navbar-content %}
    <div class="navbar-left">
        <a class="btn btn-default navbar-btn" href="{% url 'compta:home' %}">{% trans "Retour" %}</a>
    </div>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-offset-3 col-md-6">
                <table class="table table-striped">
                    <caption class="text-center">{% blocktrans with libelle=compte.libelle budget=compte.total_budget solde=compte.solde %}Répartition {{ libelle }} (solde = {{ solde }}€) pour un budget prévu de {{ budget }}€{% endblocktrans %}</caption>
                    <thead>
                    <tr>
                        <th>{% trans "Personne" %}</th>
                        <th>{% trans "Salaire" %}</th>
                        <th>{% trans "Part" %}</th>
                        <th>{% trans "Avances" %}</th>
                        <th>{% trans "A verser" %}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for utilisateur in compte.utilisateurs_list %}
                        <tr>
                            <td>{{ utilisateur.first_name }}</td>
                            <td>{{ utilisateur.revenus_personnels }}€</td>
                            <td>{{ utilisateur.part|times:100|floatformat:2 }}%</td>
                            <td>{{ utilisateur.avances }}€</td>
                            <td>{{ utilisateur.a_verser|floatformat:0 }}€ <span data-toggle="tooltip" data-placement="right" title="{{ utilisateur.formule_calcule_a_verser }}">{% bootstrap_icon 'zoom-in' %}</span></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                    <tfoot>
                        <tr>
                            <td><strong>{% trans 'Total' %}</strong></td>
                            <td>{{ compte.total_salaire }}€</td>
                            <td>{{ compte.total_part|times:100|floatformat:2 }}%</td>
                            <td>{{ compte.total_avances }}€</td>
                            <td>{{ compte.total_a_verser|floatformat:0 }}€</td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

compta/templates/compta/operations.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load bootstrap3 %}
{% load utils %}

{% block navbar-content %}
    <div class="navbar-left">
        <a class="btn btn-default navbar-btn" href="{% url 'compta:home' %}">{% trans "Retour" %}</a>
    </div>
{% endblock %}

{% block content %}
    <div class="container">
        <p class="lead text-center">{{ compte.libelle }} : <span class="{% if compte.solde >= 0 %}text-success{% else %}text-danger{% endif %}">{{ compte.solde }}€</span></p>

        <div class="row">
            <div class="col-md-offset-1 col-md-10">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>{% trans "Libellé" %}</th>
                        <th>{% trans "Date" %}</th>
                        <th>{% trans "Montant" %}</th>
                        <th>{% trans "Catégorie" %}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for operation in operations %}
                        <tr>
                            <td>{{ operation.libelle }}</td>
                            <td>{{ operation.date_operation }}</td>
                            <td><span class="{% if operation.montant >= 0 %}text-success{% else %}text-danger{% endif %}">{{ operation.montant }}€</span></td>
                            <td>
                                <form>
                                    {% csrf_token %}
                                    {% bootstrap_field operation.categorie_form.operation_id show_label=False layout='inline' %}
                                    {% bootstrap_field operation.categorie_form.redirect show_label=False layout='inline' %}
                                    {% bootstrap_field operation.categorie_form.categorie show_label=False layout='inline' %}
                                </form>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

                <div class="text-center">
                    {% bootstrap_pagination page_obj %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_script %}
    <script type="text/javascript">
        $(function () {
            $(document).on('change', "select[name='categorie']", function() {
                $.post('{% url 'compta:edit-categorie' %}', $(this.closest("form")).serialize(), function(data) {});
            });
        });
    </script>
{% endblock %}

compta/templates/compta/operations_epargne.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load bootstrap3 %}
{% load utils %}

{% block navbar-content %}
    <div class="navbar-left">
        <a class="btn btn-default navbar-btn" href="{% url 'compta:home' %}">{% trans "Retour" %}</a>
    </div>
{% endblock %}

{% block content %}
    <div class="container">
        <p class="lead text-center">{{ epargne.categorie.libelle }} : <span class="{% if epargne.solde >= 0 %}text-success{% else %}text-danger{% endif %}">{{ epargne.solde }}€</span></p>

        <div class="row">
            <div class="col-md-offset-1 col-md-10">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>{% trans "Compte" %}</th>
                        <th>{% trans "Libellé" %}</th>
                        <th>{% trans "Date" %}</th>
                        <th>{% trans "Montant" %}</th>
                        <th>{% trans "Montant de l'opération initiale" %}</th>
                        <th>{% trans "Pourcentage de l'opération initiale" %}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for operation in operations %}
                        <tr>
                            <td>{{ operation.operation.compte.libelle }}</td>
                            <td>{{ operation.operation.libelle }}</td>
                            <td>{{ operation.operation.date_operation }}</td>
                            <td><span class="{% if operation.montant >= 0 %}text-success{% else %}text-danger{% endif %}">{{ operation.montant }}€</span></td>
                            <td><span class="{% if operation.operation.montant >= 0 %}text-success{% else %}text-danger{% endif %}">{{ operation.operation.montant }}€</span></td>
                            <td>{{ operation.part|times:100|floatformat:0 }}%</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

                <div class="text-center">
                    {% bootstrap_pagination page_obj %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}